### ISSUE TITLE
permission denied during install

### ISSUE THREAD

**Issue by colindaven** [nanoporetech/bonito#78] opened 2020-11-27 10:00 UTC
Hi,
I was surprised by this permission denied error attempting install on a fairly mint Ubuntu 20.04 server:

Is install as --user not allowed ?

cheers,
Colin

```
$ pip3 install --user ont-bonito

Collecting ont-bonito
  Downloading ont-bonito-0.3.1.tar.gz (35 kB)
Collecting crf-beam==0.0.1a0
  Downloading crf_beam-0.0.1a0-cp38-cp38-manylinux1_x86_64.whl (128 kB)
     |████████████████████████████████| 128 kB 7.8 MB/s
Collecting fast-ctc-decode==0.2.5
  Downloading fast_ctc_decode-0.2.5-cp38-cp38-manylinux1_x86_64.whl (366 kB)
     |████████████████████████████████| 366 kB 11.8 MB/s
Collecting mappy==2.17
  Downloading mappy-2.17.tar.gz (199 kB)
     |████████████████████████████████| 199 kB 18.9 MB/s
Collecting numpy<=1.18.5
  Downloading numpy-1.18.5-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
     |████████████████████████████████| 20.6 MB 18.5 MB/s
Collecting ont-fast5-api==3.1.6
  Downloading ont_fast5_api-3.1.6-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 13.4 MB/s
Collecting optuna==1.1.0
  Downloading optuna-1.1.0.tar.gz (135 kB)
     |████████████████████████████████| 135 kB 17.1 MB/s
Collecting parasail==1.2
  Downloading parasail-1.2-py2.py3-none-manylinux2010_x86_64.whl (14.1 MB)
     |████████████████████████████████| 14.1 MB 10.4 MB/s
Requirement already satisfied: requests==2.22.0 in /usr/lib/python3/dist-packages (from ont-bonito) (2.22.0)
Collecting seqdist==0.0.1
  Downloading seqdist-0.0.1-py3-none-any.whl (21 kB)
Collecting toml==0.10.0
  Downloading toml-0.10.0-py2.py3-none-any.whl (25 kB)
Collecting torch<=1.5,>=1.1.0
  Downloading torch-1.5.0-cp38-cp38-manylinux1_x86_64.whl (752.0 MB)
     |████████████████████████████████| 752.0 MB 3.9 kB/s
Collecting tqdm==4.31.1
  Downloading tqdm-4.31.1-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 1.7 MB/s
Collecting Cython>=0.25.2
  Downloading Cython-0.29.21-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 16.5 MB/s
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting h5py>=2.6
  Downloading h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 15.0 MB/s
Collecting progressbar33>=2.3.1
  Downloading progressbar33-2.4.tar.gz (10 kB)
Collecting alembic
  Downloading alembic-1.4.3-py2.py3-none-any.whl (159 kB)
     |████████████████████████████████| 159 kB 16.9 MB/s
Collecting cliff
  Downloading cliff-3.5.0-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 3.6 MB/s
Collecting colorlog
  Downloading colorlog-4.6.2-py2.py3-none-any.whl (10.0 kB)
Collecting joblib
  Downloading joblib-0.17.0-py3-none-any.whl (301 kB)
     |████████████████████████████████| 301 kB 19.0 MB/s
Collecting scipy!=1.4.0
  Downloading scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
     |████████████████████████████████| 25.8 MB 19.2 MB/s
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/lib/python3/dist-packages (from optuna==1.1.0->ont-bonito) (1.3.12)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from parasail==1.2->ont-bonito) (0.34.2)
Collecting cupy-cuda102
  Downloading cupy_cuda102-8.2.0-cp38-cp38-manylinux1_x86_64.whl (121.8 MB)
     |████████████████████████████████| 121.8 MB 79 kB/s
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from torch<=1.5,>=1.1.0->ont-bonito) (0.18.2)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 1.4 MB/s
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from packaging->ont-fast5-api==3.1.6->ont-bonito) (1.14.0)
Collecting python-editor>=0.3
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting Mako
  Downloading Mako-1.1.3-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 1.4 MB/s
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 19.5 MB/s
Collecting stevedore>=2.0.1
  Downloading stevedore-3.2.2-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 351 kB/s
Collecting cmd2!=0.8.3,>=0.8.0
  Downloading cmd2-1.4.0-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 21.0 MB/s
Collecting pbr!=2.1.0,>=2.0.0
  Downloading pbr-5.5.1-py2.py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 10.6 MB/s
Requirement already satisfied: PyYAML>=3.12 in /usr/lib/python3/dist-packages (from cliff->optuna==1.1.0->ont-bonito) (5.3.1)
Collecting PrettyTable<0.8,>=0.7.2
  Downloading prettytable-0.7.2.tar.bz2 (21 kB)
Collecting fastrlock>=0.3
  Downloading fastrlock-0.5-cp38-cp38-manylinux1_x86_64.whl (31 kB)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/lib/python3/dist-packages (from Mako->alembic->optuna==1.1.0->ont-bonito) (1.1.0)
Requirement already satisfied: colorama>=0.3.7 in /usr/lib/python3/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna==1.1.0->ont-bonito) (0.4.3)
Requirement already satisfied: attrs>=16.3.0 in /usr/lib/python3/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna==1.1.0->ont-bonito) (19.3.0)
Collecting pyperclip>=1.6
  Downloading pyperclip-1.8.1.tar.gz (20 kB)
Collecting wcwidth>=0.1.7
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Building wheels for collected packages: ont-bonito, mappy, optuna, progressbar33, PrettyTable, pyperclip
  Building wheel for ont-bonito (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/working2/rcug/scratch/tmp/pip-install-ogfapw6i/ont-bonito/setup.py'"'"'; __file__='"'"'/working2/rcug/scratch/tmp/pip-install-ogfapw6i/ont-bonito/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /working2/rcug/scratch/tmp/pip-wheel-cs4axzu6
       cwd: /working2/rcug/scratch/tmp/pip-install-ogfapw6i/ont-bonito/
  Complete output (93 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/bonito
  copying bonito/__init__.py -> build/lib/bonito
  copying bonito/nn.py -> build/lib/bonito
  copying bonito/fast5.py -> build/lib/bonito
  copying bonito/training.py -> build/lib/bonito
  copying bonito/util.py -> build/lib/bonito
  copying bonito/aligner.py -> build/lib/bonito
  copying bonito/multiprocessing.py -> build/lib/bonito
  copying bonito/io.py -> build/lib/bonito
  creating build/lib/bonito/ctc
  copying bonito/ctc/__init__.py -> build/lib/bonito/ctc
  copying bonito/ctc/basecall.py -> build/lib/bonito/ctc
  copying bonito/ctc/model.py -> build/lib/bonito/ctc
  creating build/lib/bonito/crf
  copying bonito/crf/__init__.py -> build/lib/bonito/crf
  copying bonito/crf/basecall.py -> build/lib/bonito/crf
  copying bonito/crf/model.py -> build/lib/bonito/crf
  creating build/lib/bonito/cli
  copying bonito/cli/evaluate.py -> build/lib/bonito/cli
  copying bonito/cli/view.py -> build/lib/bonito/cli
  copying bonito/cli/convert.py -> build/lib/bonito/cli
  copying bonito/cli/pair.py -> build/lib/bonito/cli
  copying bonito/cli/basecaller.py -> build/lib/bonito/cli
  copying bonito/cli/__init__.py -> build/lib/bonito/cli
  copying bonito/cli/download.py -> build/lib/bonito/cli
  copying bonito/cli/tune.py -> build/lib/bonito/cli
  copying bonito/cli/train.py -> build/lib/bonito/cli
  running egg_info
  writing ont_bonito.egg-info/PKG-INFO
  writing dependency_links to ont_bonito.egg-info/dependency_links.txt
  writing entry points to ont_bonito.egg-info/entry_points.txt
  writing requirements to ont_bonito.egg-info/requires.txt
  writing top-level names to ont_bonito.egg-info/top_level.txt
  reading manifest file 'ont_bonito.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'ont_bonito.egg-info/SOURCES.txt'
  creating build/lib/bonito/data
  copying bonito/data/README.md -> build/lib/bonito/data
  creating build/lib/bonito/models
  copying bonito/models/README.md -> build/lib/bonito/models
  creating build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v1.toml -> build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v2.toml -> build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v3.toml -> build/lib/bonito/models/configs
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/__init__.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/nn.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/fast5.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/training.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/util.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/aligner.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/multiprocessing.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/io.py -> build/bdist.linux-x86_64/wheel/bonito
  creating build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/basecall.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/model.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  creating build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/basecall.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/model.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  creating build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/evaluate.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/view.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/convert.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/pair.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/basecaller.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/download.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/tune.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/train.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  creating build/bdist.linux-x86_64/wheel/bonito/data
  copying build/lib/bonito/data/README.md -> build/bdist.linux-x86_64/wheel/bonito/data
  creating build/bdist.linux-x86_64/wheel/bonito/models
  copying build/lib/bonito/models/README.md -> build/bdist.linux-x86_64/wheel/bonito/models
  creating build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v1.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v2.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v3.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  running install_egg_info
  Copying ont_bonito.egg-info to build/bdist.linux-x86_64/wheel/ont_bonito-0.3.1.egg-info
  running install_scripts
  error: [Errno 13] Permission denied: 'bonito'
  ----------------------------------------
  ERROR: Failed building wheel for ont-bonito
  Running setup.py clean for ont-bonito
  Building wheel for mappy (setup.py) ... done
  Created wheel for mappy: filename=mappy-2.17-cp38-cp38-linux_x86_64.whl size=613292 sha256=d2ab6c12d93e26bf259fecc2ed115c598bc02a878700dff161a914cffd0e0778
  Stored in directory: /home/rcug/.cache/pip/wheels/bc/3e/d0/6f861d46f085c99d4de1128dc9c020a80ad206a85d638f5cf1
  Building wheel for optuna (setup.py) ... done
  Created wheel for optuna: filename=optuna-1.1.0-py3-none-any.whl size=187206 sha256=efde583e5fe26e7788600d9bd34cd0b2d0eeb7b5c4ed86229bde2d2a05748999
  Stored in directory: /home/rcug/.cache/pip/wheels/27/5d/70/8df430e595983c4263052277258a0260e21c59b74da7ac44c0
  Building wheel for progressbar33 (setup.py) ... done
  Created wheel for progressbar33: filename=progressbar33-2.4-py3-none-any.whl size=12150 sha256=a9b53e16e42c580dfc0dd21b02db521805da335f324a9381c393ac51603c3e65
  Stored in directory: /home/rcug/.cache/pip/wheels/29/a7/e5/80302edade245519d68bbdf44f7879049f9b67e7bae7ed66e4
  Building wheel for PrettyTable (setup.py) ... done
  Created wheel for PrettyTable: filename=prettytable-0.7.2-py3-none-any.whl size=13698 sha256=f5eb36e1e953fc718b9f47b8d3a4127d79bbdcba46ee84d59a1ebb24d4ae4b28
  Stored in directory: /home/rcug/.cache/pip/wheels/46/60/6c/bb25d05df22906786206e901e9354bb3061061191116768bee
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.1-py3-none-any.whl size=11118 sha256=8ced3b4f1253930456d992b3626378ae77b746fe5592b142bc01ec8d496a5c9f
  Stored in directory: /home/rcug/.cache/pip/wheels/67/0c/ba/1468f38115898442e13f99a19a8dcf1e0ca73488053ef7b388
Successfully built mappy optuna progressbar33 PrettyTable pyperclip
Failed to build ont-bonito
Installing collected packages: numpy, Cython, crf-beam, fast-ctc-decode, mappy, pyparsing, packaging, h5py, progressbar33, ont-fast5-api, python-editor, Mako, python-dateutil, alembic, pbr, stevedore, pyperclip, wcwidth, cmd2, PrettyTable, cliff, colorlog, joblib, scipy, tqdm, optuna, parasail, fastrlock, cupy-cuda102, torch, seqdist, toml, ont-bonito
    Running setup.py install for ont-bonito ... done
Successfully installed Cython-0.29.21 Mako-1.1.3 PrettyTable-0.7.2 alembic-1.4.3 cliff-3.5.0 cmd2-1.4.0 colorlog-4.6.2 crf-beam-0.0.1a0 cupy-cuda102-8.2.0 fast-ctc-decode-0.2.5 fastrlock-0.5 h5py-3.1.0 joblib-0.17.0 mappy-2.17 numpy-1.18.5 ont-bonito-0.3.1 ont-fast5-api-3.1.6 optuna-1.1.0 packaging-20.4 parasail-1.2 pbr-5.5.1 progressbar33-2.4 pyparsing-2.4.7 pyperclip-1.8.1 python-dateutil-2.8.1 python-editor-1.0.4 scipy-1.5.4 seqdist-0.0.1 stevedore-3.2.2 toml-0.10.0 torch-1.5.0 tqdm-4.31.1 wcwidth-0.2.5

```

**Comment by colindaven** [comment] 2020-11-27 10:09
Might not be so relevant since I'm going for the CPU only variant, so am now following this:

https://github.com/nanoporetech/bonito/issues/70

**Comment by hermannschwaerzlerUIBK** [comment] 2020-12-01 10:11
I think this is a duplicate of #74.
The wheel installation is somehow borked...

**Closed** 2021-01-29 16:29 UTC
