### ISSUE TITLE
Fewer total bases called when using bonito models compared to default guppy models

### ISSUE THREAD

**Issue by danrdanny** [nanoporetech/bonito#119] opened 2021-02-14 02:39 UTC
Hi all, I've been working on understanding why my average coverage has been lower after switching to basecalling using bonito v031 models. I am curious if other users are seeing the same issue. This is consistent for mouse and human samples, and across ten or so samples I've checked. If this is a guppy issue, I am happy to post in the community. 

Briefly, the total number of bases called for any experiment is relatively similar when I compare output from guppy 3.6.1, 4.0.11, and 4.4.0 using the default config file, but drops by ~15% when using the bonito 031 config files. The total number of reads is always the same regardless of config used. The data is from an adaptive sampling experiment in a human, thus the average read length is low.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/3186059/107866841-f51d8880-6e29-11eb-9ad9-f30517bfe7d6.png">

I can give more examples, but the percentage drop in total bases called will be the same. Thoughts, suggestions? Thanks in advance.

**Comment by iiSeymour** [comment] 2021-02-14 11:45
Hey @danrdanny - have you also compared aligned lengths?

**Comment by danrdanny** [comment] 2021-02-14 23:08
Really good question @iiSeymour. I hadn't, but here's a summary for two samples. Both basecalled with guppy 4.4.0, one with the default model and the other with bonito. Aligned using minimap2 to hg38. I used `samtools view -F 4` to only look at mapped reads. These are both adaptive sampling experiments, so the huge difference between all bases and >1kb is expected. Interesting that the percent bases lost isn't linear.

Should I be looking at this in a different way? Anyone able to replicate this?

<img width="490" alt="image" src="https://user-images.githubusercontent.com/3186059/107891726-4a62a400-6ed5-11eb-8c51-0508a4692c3a.png">

**Comment by danrdanny** [comment] 2021-02-16 18:29
If it's helpful here's a plot of read lengths from two fastq files, one called with guppy 4.4.0 and the other with guppy 4.4.0 using bonito 0.3.1 model. Sample is the same, this is adaptive sampling data.  I cut the x-axis off at 1kb. There's a left shift but also a peak of read lengths <100bp.

![image](https://user-images.githubusercontent.com/3186059/108105515-94689880-7041-11eb-8eeb-9a0ea4266f93.png)

**Comment by gallardo-seq** [comment] 2021-02-17 20:50
We tried the CRF models on Guppy and we're observing the same phenomenon. Even though the number of reads is identical, the read length of the resulting basecalls is around 40% shorter. Table below based on seqkit stats results:

![image](https://user-images.githubusercontent.com/69699784/108266248-b84ddc00-711e-11eb-8f41-ecf509ed5bc4.png)

**Comment by iiSeymour** [comment] 2021-02-23 17:39
@danrdanny @gallardo-seq I've failed to find datasets to reproduce this so far but I do have some new models which may help. Are either of you able to test these in bonito or do you need a guppy/rerio model?

**Comment by danrdanny** [comment] 2021-02-23 17:43
@iiSeymour thanks. I would prefer a guppy model as bonito frequently crashes my system. I can also share fast5 data with you if you want to see if you can replicate what I'm seeing.

**Comment by iiSeymour** [comment] 2021-02-23 17:51
A fast5 file would really help thanks - https://nanoporetech.ent.box.com/f/7c4375e2b71b48258ebed29f198b89ab

**Comment by gallardo-seq** [comment] 2021-02-24 18:58
@iiSeymour I saw that a new version of bonito is up with new models, I will go ahead and try running my test dataset again to see if I can replicate the issue.

**Comment by Sumsarium** [comment] 2021-02-24 21:26
hi @iiSeymour ...do you by any chance have a guppy/rerio (compatible) model for the newest bonito model (dna_r9.4.1@v3.2)?

**Comment by callumparr** [comment] 2021-02-27 14:00
> hi @iiSeymour ...do you by any chance have a guppy/rerio (compatible) model for the newest bonito model (dna_r9.4.1@v3.2)?

Would also like this. I am about to embark on recalling lots of old runs and if the update models are to be transferred to rerio repository soon I will wait until then

**Comment by iiSeymour** [comment] 2021-03-01 11:33
@Sumsarium @callumparr models pushed to rerio this morning.

**Comment by gallardo-seq** [comment] 2021-03-23 01:17
![Screen Shot 2021-03-22 at 6 09 48 PM](https://user-images.githubusercontent.com/69699784/112077479-d81b5a00-8b39-11eb-90db-d61d4ffbf52e.png)
@iiSeymour I tried the new guppy CRF model (v032) and there's a noticeable improvement in the base yield (sum_len) and N50 values.

For transparency purposes, the length of the resulting reads is important for us since we're doing a concatemer-based approach for error correction of single molecule reads (https://www.biorxiv.org/content/10.1101/2021.01.27.428469v1.full). I'll put these new crf_v032 basecalls through our pipeline, hopefully we can see improvements on the other ends.

Also, this might be a question for @cjw85, but are there any medaka models available for crf_v032 guppy basecalls?

**Comment by iiSeymour** [comment] 2021-04-21 10:01
The new models in [v0.3.7](https://github.com/nanoporetech/bonito/releases/tag/v0.3.7) do a much better job here - thanks @danrdanny for the dataset, it was really helpful.

**Comment by callumparr** [comment] 2021-04-22 14:44
somewhat related. I ran some data set through guppy 4.4.1 (I think) with either flipflop HAC or using rerio directory for bonito crf32. There seem to be some disagreement in reads below a certain length and large spike in reads of 1 or few nucleotides long. From bioanalyzer of the prepared cDNA library I was expected quite bum at 300nt mark as seen in the read length distribution with flipflop but this is dramatically reduced with bonito

Does bonito not do well with small reads like older guppy versions? 

![Unknown](https://user-images.githubusercontent.com/41637575/115734230-7f531180-a3c4-11eb-9e52-322f800dc28e.png)

Full NanoComp stats of the FASTQs is here 

[NanoStats.txt](https://github.com/nanoporetech/bonito/files/6359164/NanoStats.txt)

**Comment by danrdanny** [comment] 2021-04-22 15:03
@callumparr, I think you should try with the 3.3 models in bonito 0.3.7. I'm basecalling now and will also compare.

**Comment by gallardo-seq** [comment] 2021-04-29 01:15
![image](https://user-images.githubusercontent.com/69699784/116490873-58c22a00-a84d-11eb-95a0-c5b2aaf5a80e.png)
I re-run my samples with the CRF v3.3 model, as you can see the lengths are now comparable with Guppy (great news!). The only thing is that the qualities dropped down significantly. This was using Guppy 4.5.4 with the bonito 0.3.7 model exported .jsn file, so my guess is the quality is not meaningful here? (especially since this was not an official rerio release?)

**Comment by iiSeymour** [comment] 2021-04-29 08:20
@gallardo-seq that looks much better, thanks for reporting. Yes, that is correct, it's not calibrated correctly.

**Comment by iiSeymour** [comment] 2022-09-05 15:24
The short read performance in bonito v0.6 is now much improved.

**Closed by iiSeymour** 2022-09-05 15:24 UTC
